module.exports = {
  bodyParser: require("body-parser"),
  compression: require("compression"),
  cors: require("cors"),
  CryptoJS: require("crypto-js"),
  dotenv: require("dotenv"),
  express: require("express"),
  helmet: require("helmet"),
  jwt: require("jsonwebtoken"),
  mongoose: require("mongoose"),
  morgan: require("morgan"),
  nodemailer: require("nodemailer"),
  twilio: require("twilio"),
  cron: require("node-cron"),
};
